### ISSUE TITLE
想问一下Tomcat7.X能支持吗？

### ISSUE THREAD

**Issue by b1412** [wjw465150/RedisManager#1]
RT

**Comment by wjw465150** [comment]
你好:
   master分支是支持Tomcat6.x
   tomcat7分支是支持Tomcat7.x的

2013/8/14 KidZhou notifications@github.com

> RT
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wjw465150/RedisManager/issues/1
> .

## 

wstone

**Comment by b1412** [comment]
谢谢，看到了~，准备研究一下怎么用，有问题还请不惜赐教

**Comment by wjw465150** [comment]
速度很快,已经用在不少大型的web网站上,跟其他利用Redis存储Session的方式都不同,建议你仔细读读源代码!

2013/8/15 KidZhou notifications@github.com

> 谢谢，看到了~，准备研究一下怎么用，有问题还请不惜赐教
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wjw465150/RedisManager/issues/1#issuecomment-22680085
> .

## 

wstone

**Comment by wjw465150** [comment]
https://github.com/wjw465150/RedisManager/tree/Tomcat7

2014-11-14 15:09 GMT+08:00 xiafei5688 notifications@github.com:

> 您好，哪里可以下支持tomcat7的
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wjw465150/RedisManager/issues/1#issuecomment-63018227
> .

## 

wstone
