### ISSUE TITLE
请问是否只需要拷贝wjw-redismanager.jar到tomcat下的lib目录

### ISSUE THREAD

**Issue by jbasttdi** [wjw465150/RedisManager#2]
你好，是否只需要拷贝wjw-redismanager.jar这个文件就行了，其它的一些lib包不需要放到tomcat的lib目录下吗？
我试着只放那一个文件到tomcat的lib目录下，也可以运行，session数据会存放到redis中，但挺奇怪的为什么不需要其它lib文件也能运行呢。
谢谢！

**Comment by wjw465150** [comment]
呵呵,谢谢你的提问,所有的依赖都打包到一个wjw-redismanager.jar文件里了!你可以仔细看看ant配置文件:ant_build.xml!

在 2014年4月17日 上午8:42，jbasttdi notifications@github.com写道：

> 你好，是否只需要拷贝wjw-redismanager.jar这个文件就行了，其它的一些lib包不需要放到tomcat的lib目录下吗？
> 我试着只放那一个文件到tomcat的lib目录下，也可以运行，session数据会存放到redis中，但挺奇怪的为什么不需要其它lib文件也能运行呢。
> 谢谢！
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wjw465150/RedisManager/issues/2
> .

## 

wstone

**Comment by jbasttdi** [comment]
谢了，已经在Windows和Linux环境配置成功，会自动把Session存进Redis中。
还有个问题想请教一下，

```
    <Manager pathname="" className="org.apache.catalina.session.ext.RedisManager" stickySession="true" serverlist="127.0.0.1:6379" minConn="5" maxConn="100" socketTO="6000" debug="false"/>
```

这个是支持redis的集群配置方式吧，那是否支持Tomcat的集群?

**Comment by wjw465150** [comment]
当然支持了,你好好看看readme.md

在 14/4/17，jbasttdinotifications@github.com 写道：

> 谢了，已经在Windows和Linux环境配置成功，会自动把Session存进Redis中。
> 还有个问题想请教一下，
> 
> ```
>     <Manager pathname=""
> className="org.apache.catalina.session.ext.RedisManager"
> stickySession="true" serverlist="127.0.0.1:6379" minConn="5" maxConn="100"
> socketTO="6000" debug="false"/>
> ```
> 
> 这个是支持redis的集群配置方式吧，那是否支持Tomcat的集群?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/2#issuecomment-40682392

## 

wstone

**Comment by wenhui01** [comment]
还是不知道tomcat如何集群配置，session共享是如何实现，麻烦高手指点一下，嘻嘻

**Comment by wenhui01** [comment]
能给出具体的tomcat配置方式么？

**Comment by wjw465150** [comment]
1. 复制:wjw-redismanager.jar到lib下面
2. conf下文件context.xml中添加:
   
   
   
   <Manager pathname=""
   className="org.apache.catalina.session.ext.RedisManager"
            stickySession="true"
   serverlist="${ip1}:${port1},${ip2}:${port2}" minConn="5" maxConn="100"
   socketTO="6000" debug="false"

**Comment by wenhui01** [comment]
谢了，用起来确实很方便，还想问下，不同tomcat实现redis session共享，还需要一些什么配置么？

**Comment by wjw465150** [comment]
没有

在 14/4/25，wenhui01notifications@github.com 写道：

> 谢了，用起来确实很方便，还想问下，不同tomcat实现redis session共享，还需要一些什么配置么？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/2#issuecomment-41356410

## 

wstone
