### ISSUE TITLE
请问能够支持两台redis服务器吗？

### ISSUE THREAD

**Issue by xiafei5688** [wjw465150/RedisManager#3]
请问你是采用复制session到每个tomcat的方式吗？

**Comment by wjw465150** [comment]
当然可以支持多台redis服务器了!

2014-11-08 16:33 GMT+08:00 xiafei5688 notifications@github.com:

> 配置文件里面的serverlist这个属性应该是可以配置多台redis吧？
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wjw465150/RedisManager/issues/3.

## 

wstone

**Comment by wjw465150** [comment]
没看到效果?你怎么看的!粘性session的意思是针对同一个session,它所有的请求都会在一个固定的机器上

2014-11-14 13:56 GMT+08:00, xiafei5688 notifications@github.com:

> stickySession="true"  这个是设置粘性session吧？我设置后，没看到效果。是否还需要配置什么？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/3#issuecomment-63014165

## 

wstone

**Comment by wjw465150** [comment]
你的redis需要配置成HA(高和用)

在 14/11/17，xiafei5688notifications@github.com 写道：

> 我配置了两台redis服务器，使用serverlist这个属性配置上两台redis的IP和端口。运行web应用，然后断掉其中一台redis，之后tomcat就一直报错了。还需要什么特殊设置吗
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/3#issuecomment-63257342

## 

wstone

**Comment by wjw465150** [comment]
这一布你做了吗?每天tomcat的节点号都不能一样!
2. x:\apache-tomcat-7.X.XX\conf下文件server.xml中更改<Engine>添加jvmRoute属性:
    <Engine name="Catalina" defaultHost="localhost" jvmRoute="jvm${节点号}">

在 14/11/17，xiafei5688notifications@github.com 写道：

> 那粘性设置的呢。我配置了3台tomcat，每台都设置
> stickySession="true"；但是请求是三台tomcat都有机会得到，没有固定到某一台tomcat。
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/3#issuecomment-63266157

## 

wstone

**Comment by wjw465150** [comment]
还有,你tomcat前端必须要有反向代理,而且反向代理的负载均衡算法必须是ip Hash!

在 2014年11月17日 下午3:55，王俊伟 wjw465150@gmail.com写道：

> 这一布你做了吗?每天tomcat的节点号都不能一样!
> 2. x:\apache-tomcat-7.X.XX\conf下文件server.xml中更改<Engine>添加jvmRoute属性:
>     <Engine name="Catalina" defaultHost="localhost" jvmRoute="jvm${节点号}">
> 
> 在 14/11/17，xiafei5688notifications@github.com 写道：
> 
> > 那粘性设置的呢。我配置了3台tomcat，每台都设置
> > stickySession="true"；但是请求是三台tomcat都有机会得到，没有固定到某一台tomcat。
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/wjw465150/RedisManager/issues/3#issuecomment-63266157
> 
> ## 
> 
> wstone

## 

wstone

**Comment by xiafei5688** [comment]
你们Ha是用sentinel 这个方式配置吗

**Comment by wjw465150** [comment]
keepalived

2014-11-18 15:02 GMT+08:00, xiafei5688 notifications@github.com:

> 你们Ha是用sentinel 这个方式配置吗
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/3#issuecomment-63430350

## 

wstone

**Comment by wjw465150** [comment]
感觉你缺少分布式缓存的基本知识,建议你先到网上查查"一致性Hash",再看看jedis源代码以及例子,就明白了!

在 14/11/18，xiafei5688notifications@github.com 写道：

>  serverlist="IP1:6379,IP2:6379"
> ，这个问题我还是没搞明白。当IP1宕掉了，redismanager怎么能够是用ip2的redis,并且要怎么使tomcat不报错呢
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/3#issuecomment-63434865

## 

wstone

**Comment by wjw465150** [comment]
无语,你先看看jedis的API

2014-11-19 11:21 GMT+08:00, tommin notifications@github.com:

> serverlist="IP1:6379,IP2:6379"    这个属性跟一致性hash有什么关系吗
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/3#issuecomment-63586629

## 

wstone

**Comment by gglzf4** [comment]
我测试发现，在服务器创建session后，如果session之后没有执行过set，那么这个session是不会序列化到redis，当每执行过一次set操作后才会序列化到redis。这就应该就是你说的“前端反向代理的负载均衡算法必须是ip Hash!”的原因吧，其实就是需要把用户请求固定到某一台tomcat上吧！这样理解正确不？

**Comment by wjw465150** [comment]
是的,要不然,session来回跳,你受得了啊!

在 14/12/11，锐敏notifications@github.com 写道：

> 我测试发现，在服务器创建session后，如果session之后没有执行过set，那么这个session是不会序列化到redis，当每执行过一次set操作后才会序列化到redis。这就应该就是你说的“前端反向代理的负载均衡算法必须是ip
> Hash!”的原因吧，其实就是需要把用户请求固定到某一台tomcat上吧！这样理解正确不？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/3#issuecomment-66599361

## 

wstone
