### ISSUE TITLE
请问下session过期时间，怎么用redismanager 控制？

### ISSUE THREAD

**Issue by xiafei5688** [wjw465150/RedisManager#4]
请问下session过期时间，怎么用redismanager 控制？

**Comment by wjw465150** [comment]
不需要redismanager控制,控制sessio的过期时间在web.xml里

2014-11-24 14:08 GMT+08:00, tommin notifications@github.com:

> 请问下session过期时间，怎么用redismanager 控制？
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/wjw465150/RedisManager/issues/4

## 

wstone
