### ISSUE TITLE
下载源码后，gradle打包时，jar总是SKIPPPED

### ISSUE THREAD

**Issue by jiamine** [wjw465150/RedisManager#7]
[root@tc23240 RedisManager]# gradle jar
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_5swzhiatqlmxi9gvcmf08ckki.run(/root/RedisManager/build.gradle:39)
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.5
1 warning
:processResources
:classes
:jar SKIPPED

**Comment by wjw465150** [comment]
Please Use the Gradle version below 5.0, for example: 4.10!
